apiVersion: apps/v1
kind: Deployment
metadata: 
   name: ipweek2-mongo-database-deployment
spec:
   selector:
      matchLabels:
        app:  ipweek2-mongo-database
   replicas: 1    
   template: 
       metadata:
         labels:
            app: ipweek2-mongo-database
       spec: 
          containers:
           -  name: ipweek2-mongo-database
              image: mongo
              ports:
                - containerPort: 27017
              resources:
                limits:
                   cpu: "1"
                   memory: "1Gi"
              requests:
                   cpu: "0.5"
                   memory: "512Mi" 
   volumeMounts:
            - name: mongodb-data
              mountPath: /data/db   
   volumeClaimTemplates:
          - metadata:
             name: mongodb-data
             spec:
                accessModes:
                - "ReadWriteOnce"
            resources:
            requests:
              storage: 1Gi
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom: 
                     secretKeyRef:
                         name: ipweek2-mongo-secrets  
                         key:  MONGO_INITDB_ROOT_USERNAME
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom: 
                     secretKeyRef:
                         name: ipweek2-mongo-secrets  
                         key:  MONGO_INITDB_ROOT_PASSWORD         



